# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration.html
#
nix:
  enable: true
  pure: true
  add-gc-roots: true
  path: [/home/chris/nix/path]
  packages:
    - postgresql
    - zlib

recommend-stack-upgrade: false
